backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "obras"
    label: "Obras"
    folder: "obras"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Descripción", name: "body", widget: "markdown" }
